export const expertiseSuggestions = [
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Data Analysis",
  "Machine Learning",
  "Cloud Architecture",
  "DevOps",
  "Project Management",
  "Digital Marketing",
  "Content Writing",
  "Graphic Design",
  "Database Management",
  "System Administration",
  "Network Security",
  "Software Testing",
  "Business Analysis",
  "Agile Methodologies",
  "API Development",
  "Frontend Development",
  "Backend Development"
];

export const interestSuggestions = [
  "Artificial Intelligence",
  "Blockchain Technology",
  "Virtual Reality",
  "Augmented Reality",
  "Internet of Things",
  "Quantum Computing",
  "Cybersecurity",
  "Cloud Computing",
  "Data Science",
  "Robotics",
  "Game Development",
  "Mobile Development",
  "Web3",
  "Sustainable Technology",
  "FinTech",
  "HealthTech",
  "EdTech",
  "Smart Cities",
  "Space Technology",
  "Green Technology"
];